.PHONY: clean All

All:
	@echo "----------Building project:[ 05-07-rectangle - Release ]----------"
	@$(MAKE) -f  "05-07-rectangle.mk"
clean:
	@echo "----------Cleaning project:[ 05-07-rectangle - Release ]----------"
	@$(MAKE) -f  "05-07-rectangle.mk" clean
