.PHONY: clean All

All:
	@echo "----------Building project:[ 11-03-catch - Release ]----------"
	@$(MAKE) -f  "11-03-catch.mk"
clean:
	@echo "----------Cleaning project:[ 11-03-catch - Release ]----------"
	@$(MAKE) -f  "11-03-catch.mk" clean
